public  class ForEachLoopDemo1 {
    public static  void itarateIntegerList() {
    
    
            List<integer> listInteger = new List<integer>();
            listInteger.add(10);
            listInteger.add(15);
            listInteger.add(21);
            listInteger.add(15);
            listInteger.add(15);

            for (integer eachinteger : listinteger) {
                System.debug(eachinteger);
            }

    }
}
